import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:lostfound/main.dart';
import 'package:lostfound/packages/Signin.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() {
  runApp(const SignUp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class SignUp extends StatelessWidget {
  const SignUp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {'/signin': (context) => SignIn()},
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Signup()])),
    );
  }
}

class Signup extends StatefulWidget {
  @override
  State<Signup> createState() => _SignupState();
}

class _SignupState extends State<Signup> {
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();
  final TextEditingController _confirmPasswordController =
      TextEditingController();

  /// Fonction qui gère la création d’utilisateur via Firebase
  Future<void> _registerUser() async {
    final email = _emailController.text.trim();
    final password = _passwordController.text.trim();
    final confirmPassword = _confirmPasswordController.text.trim();

    // Vérification basique : password == confirmPassword ?
    if (password != confirmPassword) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Les mots de passe ne correspondent pas.")),
      );
      return;
    }

    // Tentative de création de compte
    try {
      await FirebaseAuth.instance.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );

      // Si la création réussit, vous pouvez naviguer vers la page de SignIn
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Compte créé avec succès !")));

      // Exemple de navigation (on force l'utilisateur à aller sur l'écran SignIn):
      Navigator.pushReplacementNamed(context, '/signin');
    } catch (e) {
      // Gestion des erreurs courantes (email déjà utilisé, mot de passe trop faible...)
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Erreur : $e")));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFFFF3D9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -103,
                top: -64,
                child: Container(
                  width: 210,
                  height: 245,
                  decoration: ShapeDecoration(
                    color: const Color(0x5EF4B908),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: -105,
                child: Container(
                  width: 180,
                  height: 227,
                  decoration: ShapeDecoration(
                    color: const Color(0x49F5BA09),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 14,
                child: SizedBox(
                  width: 79,
                  child: Text(
                    '9:35',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 708,
                child: GestureDetector(
                  onTap: () {
                    // On appelle la fonction pour créer l’utilisateur
                    _registerUser();
                  },
                  child: Container(
                    width: 325,
                    height: 60,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFFCE29D),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(50),
                      ),
                    ),
                    child: Center(
                      child: Text(
                        'Sign Up',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFFAD6405),
                          fontSize: 20,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 265,
                child: Container(
                  width: 325,
                  height: 50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFCF6),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 265,
                child: SizedBox(
                  width: 290,
                  height: 50,
                  child: TextFormField(
                    controller: _nameController,
                    keyboardType: TextInputType.emailAddress,
                    style: TextStyle(
                      color: Colors.black87, // Texte saisi en foncé
                      fontSize: 16,
                    ),
                    decoration: InputDecoration(
                      hintText: 'Full Name',
                      hintStyle: TextStyle(
                        color:
                            Colors
                                .black54, // Texte d’aide (hint) légèrement plus foncé
                      ),
                      border: InputBorder.none,
                      contentPadding: EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 12,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 330,
                child: Container(
                  width: 325,
                  height: 50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFCF6),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 67,
                top: 330,
                child: SizedBox(
                  width: 290,
                  height: 50,
                  child: TextFormField(
                    controller: _emailController,
                    keyboardType: TextInputType.emailAddress,
                    style: TextStyle(color: Colors.black87, fontSize: 16),
                    decoration: InputDecoration(
                      hintText: "Enter your email",
                      hintStyle: TextStyle(color: Colors.black54),
                      border: InputBorder.none,
                      contentPadding: EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 12,
                      ),
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 34,
                top: 395,
                child: Container(
                  width: 325,
                  height: 50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFCF6),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              // Champ password
              Positioned(
                left: 61,
                top: 395,
                child: SizedBox(
                  width: 290,
                  height: 40,
                  child: TextFormField(
                    controller: _passwordController,
                    obscureText: true,
                    style: TextStyle(color: Colors.black87, fontSize: 16),
                    decoration: InputDecoration(
                      hintText: 'Enter your password',
                      hintStyle: TextStyle(color: Colors.black54),
                      border: InputBorder.none,
                      contentPadding: EdgeInsets.symmetric(horizontal: 16),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 460,
                child: Container(
                  width: 325,
                  height: 50,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFFFCF6),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              // Champ confirmation password
              Positioned(
                left: 59,
                top: 460,
                child: SizedBox(
                  width: 290,
                  height: 40,
                  child: TextFormField(
                    controller: _confirmPasswordController,
                    obscureText: true,
                    style: TextStyle(color: Colors.black87, fontSize: 16),
                    decoration: InputDecoration(
                      hintText: 'Confirm password',
                      hintStyle: TextStyle(color: Colors.black54),
                      border: InputBorder.none,
                      contentPadding: EdgeInsets.symmetric(horizontal: 16),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 3,
                top: 150,
                child: SizedBox(
                  width: 387,
                  child: Text(
                    'Get Started !',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 36,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 647,
                child: Icon(
                  Icons.check_circle,
                  size: 20,
                  color: CupertinoColors.systemYellow,
                ),
              ),
              Positioned(
                left: 70,
                top: 647,
                child: Text(
                  'I agree to the processing of ',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color.fromARGB(255, 24, 23, 23),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w200,
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 200,
                child: Text(
                  'Join us for an amazing experience',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black.withValues(alpha: 97),
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 551,
                child: Container(width: 16, height: 16, child: Stack()),
              ),
              Positioned(
                left: 160,
                top: 584,
                child: SvgPicture.asset(
                  'assets/facebookk.svg',
                  width: 32,
                  height: 32,
                ),
              ),
              Positioned(
                left: 40,
                top: 550,
                child: Text(
                  '----------------------- Or Sign in with -----------------------',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color.fromARGB(255, 24, 23, 23),
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w200,
                  ),
                ),
              ),
              Positioned(
                left: 225,
                top: 588,
                child: SvgPicture.asset(
                  'assets/google.svg',
                  width: 25,
                  height: 25,
                ),
              ),
              Positioned(
                left: 64,
                top: 547,
                child: Text(
                  'I agree to the processing of ',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black.withValues(alpha: 245),
                    fontSize: 13,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 257,
                top: 647,
                child: Text(
                  'Personal data',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF131444),
                    fontSize: 13,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 820,
                child: Text(
                  "Don't have an account ? ",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color.fromARGB(255, 24, 23, 23),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 200,
                top: 820,
                child: GestureDetector(
                  onTap: () {
                    Navigator.pushReplacement(
                      context,
                      MaterialPageRoute(builder: (context) => SignIn()),
                    );
                  },
                  child: Text(
                    "SignIn ",
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color.fromARGB(255, 0, 0, 0),
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
