import 'package:flutter/material.dart';
import 'package:lostfound/packages/Signin.dart';
import 'package:lostfound/packages/Signup.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {'/signin': (context) => SignIn()},
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [GetStarted()])),
    );
  }
}

class GetStarted extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFFFF3D9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -103,
                top: -64,
                child: Container(
                  width: 210,
                  height: 245,
                  decoration: ShapeDecoration(
                    color: const Color(0x5EF4B908),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: -105,
                child: Container(
                  width: 180,
                  height: 227,
                  decoration: ShapeDecoration(
                    color: const Color(0x49F5BA09),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 14,
                child: SizedBox(
                  width: 79,
                  child: Text(
                    '9:30',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 705,
                child: GestureDetector(
                  onTap: () {
                    Navigator.pushNamed(context, '/signin');
                  },
                  child: Container(
                    width: 325,
                    height: 60,
                    decoration: ShapeDecoration(
                      color: Color(0xFFFCE29D),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(50),
                      ),
                    ),
                    child: Center(
                      child: Text(
                        "Get Started",
                        style: TextStyle(
                          color: Colors.brown,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 88,
                top: 286,
                child: Container(
                  width: 218,
                  height: 189,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 90,
                top: 200,
                child: Image.asset(
                  "assets/up.jpg", // Remplacez par votre image
                  height: 200,
                  width: 200,
                ),
              ),
              Positioned(
                left: 3,
                top: 464,
                child: SizedBox(
                  width: 387,
                  child: Text(
                    'Find what’s lost,return what’s found\n Start your search now!',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
